language: ruby
rvm:
  - 2.1.1
services:
  - mongodb
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - sleep 15
  - mongo push_notifier_test --eval 'db.addUser("travis", "test");'
  - cp config/mongoid.yml.sample config/mongoid.yml
