# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8818b56b6b5ba878f2a9bc040b5ef06c6dd2c4a8ae255f4b978e3d391bd30bf00378c74feb11972d79d9e1a3ddc5d0d17a0580ca9114017fb818cdd490938a33
  certificate_passphrase: ef0d4a8d2c6c6

test:
  secret_key_base: 1f7a2d1c38de0a4ee155ea94e39adf3afa84e63bb09551c68030d662f1c3dcae6e6b6e99f8e1f536318f31b4f8415a68a1262c1b8602594a15a9132d3a8793e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  certificate_passphrase: <%= ENV["CERTIFICATE_PASSPHRASE"] %>
